// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCc_Z2-0ydF32cn4VRYsY2seLpCINN36I',
    appId: '1:900397271222:android:474642eeb75505dd6efe17',
    messagingSenderId: '900397271222',
    projectId: 'self-actualization-app-9dd2a',
    storageBucket: 'self-actualization-app-9dd2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwSKIPz_vblQHZnresyk943-FlYJqz6Rk',
    appId: '1:900397271222:ios:d777858279f6970e6efe17',
    messagingSenderId: '900397271222',
    projectId: 'self-actualization-app-9dd2a',
    storageBucket: 'self-actualization-app-9dd2a.firebasestorage.app',
    androidClientId: '900397271222-dh55l1ffdqt6bpqb431jl7im1karkf5u.apps.googleusercontent.com',
    iosClientId: '900397271222-g56kffhk80ga9d0co2rad1sjmv3i6e6h.apps.googleusercontent.com',
    iosBundleId: 'com.selfactualisation.app',
  );
}
